### PR TITLE
The sections until recommendation systems are updated to v0.17.5

### PR DESCRIPTION
**Pull request by semercim**
*Değişikliklerin açıklaması:*

Bu çekme talebini göndererek, bu katkıyı tercih ettiğiniz şartlar 
altında kullanabileceğinizi, değiştirebileceğinizi, kopyalayabileceğinizi 
ve yeniden dağıtabileceğinizi onaylıyorum.

### CODE REVIEW

**Review by AnirudhDagar — APPROVED** [review]
Merging!

**Comment by AnirudhDagar** [comment]
@semercim just realized the PR is made to base r17.5 branch. I'll change this to release branch and wait for the CI to pass again. r17.5 branch has no significance here, I'll remove that to avoid confusion.

**Comment by AnirudhDagar** [comment]
Since the diff is huge, can you please also take a look again once the CI is green? I'll try to merge it tomorrow.

**Comment by semercim** [comment]
> Since the diff is huge, can you please also take a look again once the CI is green? I'll try to merge it tomorrow.

@AnirudhDagar I have fixed a small typo. Except that it seems OK in a glimpse.

**Comment by AnirudhDagar** [comment]
Thanks! Bumping to v0.17.5

**Pull request merged**
