### PR TITLE
Frontpage

### PR DESCRIPTION
**Pull request by semercim**
*Değişikliklerin açıklaması:*

Bu çekme talebini göndererek, bu katkıyı tercih ettiğiniz şartlar 
altında kullanabileceğinizi, değiştirebileceğinizi, kopyalayabileceğinizi 
ve yeniden dağıtabileceğinizi onaylıyorum.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-tr/PR-13/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-tr/PR-13/

**Comment by mli** [comment]
Job d2l-tr/PR-13/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-tr/PR-13/

**Comment by astonzhang** [comment]
Looks good, thanks! However the frontpage is a bit outdated. Could you compare it with the English version: https://d2l.ai? The source is available at: https://github.com/d2l-ai/d2l-en/blob/master/static/frontpage/frontpage.html

**Comment by astonzhang** [comment]
Besides, the following guide for translation may save you some time: 
https://docs.google.com/document/d/1jjDTVH_GsHImBb_RoE1siKXdmXN8I1Bd5QN--eSG8is/edit#

Note that we made stable release versions regularly at the release branch: https://github.com/d2l-ai/d2l-en/tree/release
As of now, Chap 1--9 are almost finalized so their translation could be prioritized :)  You may git diff the latest release v0.15.1 with the version you translated to update translations, if there's any edit after the translation.

**Comment by semercim** [comment]
I have updated the frontpage to v0.15.0 (the release version) in my last PR.  The translations are from v0.14.0. We will start update them to v0.15.0 based on git diff.

**Pull request merged**
