### PR TITLE
Updating images for the Turkish release

### PR DESCRIPTION
**Pull request by semercim**
*Değişikliklerin açıklaması:*

Bu çekme talebini göndererek, bu katkıyı tercih ettiğiniz şartlar 
altında kullanabileceğinizi, değiştirebileceğinizi, kopyalayabileceğinizi 
ve yeniden dağıtabileceğinizi onaylıyorum.

### CODE REVIEW

**Comment by semercim** [comment]
@d2l-bot please rebuild :)

**Comment by semercim** [comment]
Hi @AnirudhDagar ,

It looks like I can not still use the bot's rebuild command, it does not run. Anyway, I think we need to rebuild the project to remove the cache, so that I could check whether the sphinx configuration is correct. Thanks.

**Comment by AnirudhDagar** [comment]
@d2l-bot please rebuild

**Comment by AnirudhDagar** [comment]
@semercim It doesn't work for me as well, even though the webhooks have been set correctly. I've doubled checked the settings match with d2l-en repo, so it is strange.

Anyway, for now I'll just remove the cache and rerun the PR for you.

**Comment by AnirudhDagar** [comment]
@d2l-bot please rebuild

**Comment by AnirudhDagar** [comment]
Maybe it has something to do with draft PRs? Let me try switching the draft PR.

**Comment by AnirudhDagar** [comment]
@semercim it works now (even as a draft). Please try it again, and let me know if the rebuild doesn't initiate.

**Comment by semercim** [comment]
@d2l-bot please rebuild

**Comment by semercim** [comment]
@AnirudhDagar Thanks. I can manually start the build now.

**Comment by semercim** [comment]
@d2l-bot please rebuild

**Comment by semercim** [comment]
@d2l-bot please rebuild

**Pull request merged**
